node {
    checkout scm
    pipeline = load 'jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy'
}
pipeline.multipass_pipeline([
        [job_name: 'firsttest',
         code_deploy: [
                 type: "r10k",
                 control_repo: "git@github.com:puppetlabs/puppetlabs-puppetserver_perf_control.git",
                 basedir: "/etc/puppetlabs/code-staging/environments",
                 environments: ["production"]]],
        [job_name: 'secondtest',
         code_deploy: [
                 type: "r10k",
                 control_repo: "git@github.com:puppetlabs/puppetlabs-puppetserver_perf_control.git",
                 basedir: "/etc/puppetlabs/code-staging/environments",
                 environments: ["production"]]]])
