package com.puppetlabs.gatling.node_simulations

import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

import com.puppetlabs.gatling.runner.SimulationWithScenario
import org.joda.time.LocalDateTime
import org.joda.time.format.ISODateTimeFormat
import java.util.UUID

class FOSSPuppetserver210CatalogZero extends SimulationWithScenario {

	// val httpProtocol = http
	// 	.baseURL("https://perf-bl14.delivery.puppetlabs.net:8140")
	// 	.acceptHeader("pson, yaml, binary")
	// 	.acceptEncodingHeader("gzip;q=1.0,deflate;q=0.6,identity;q=0.3")
	// 	.contentTypeHeader("application/x-www-form-urlencoded")
	// 	.userAgentHeader("Ruby")

	val headers_0 = Map("X-Puppet-Version" -> "4.1.0")

	val headers_3 = Map(
		"Accept" -> "pson, yaml, dot, binary",
		"X-Puppet-Version" -> "4.1.0")

	val headers_105 = Map(
		"Accept" -> "pson, yaml",
		"Content-Type" -> "text/pson",
		"X-Puppet-Version" -> "4.1.0",
		"Connection" -> "close")

    // val uri1 = "https://perf-bl14.delivery.puppetlabs.net:8140/puppet/v3"
	val reportBody = ELFileBody("FOSSPuppetserver210CatalogZero_0105_request.txt")

	val chain_0 = exec(http("node")
			.get("/puppet/v3/node/stfui0skrwbvd7n.delivery.puppetlabs.net?environment=production&transaction_uuid=e1c0a4a6-b57f-4dd9-b3bc-5d127fc134b3&fail_on_404=true")
			.headers(headers_0))
		.exec(http("filemeta pluginfacts")
			.get("/puppet/v3/file_metadatas/pluginfacts?environment=production&links=follow&recurse=true&source_permissions=use&ignore=.svn&ignore=CVS&ignore=.git&checksum_type=md5")
			.headers(headers_0))
		.exec(http("filemeta plugins")
			.get("/puppet/v3/file_metadatas/plugins?environment=production&links=follow&recurse=true&source_permissions=ignore&ignore=.svn&ignore=CVS&ignore=.git&checksum_type=md5")
			.headers(headers_0))
		.pause(613 milliseconds)
		.exec(http("catalog")
			.post("/puppet/v3/catalog/stfui0skrwbvd7n.delivery.puppetlabs.net")
			.headers(headers_3)
			.formParam("environment", "production")
			.formParam("facts_format", "pson")
			.formParam("facts", "%7B%22name%22%3A%22stfui0skrwbvd7n.delivery.puppetlabs.net%22%2C%22values%22%3A%7B%22puppetversion%22%3A%224.1.0%22%2C%22uniqueid%22%3A%22200a7c72%22%2C%22virtual%22%3A%22vmware%22%2C%22is_virtual%22%3Atrue%2C%22kernel%22%3A%22Linux%22%2C%22architecture%22%3A%22x86_64%22%2C%22hardwaremodel%22%3A%22x86_64%22%2C%22operatingsystem%22%3A%22CentOS%22%2C%22os%22%3A%7B%22name%22%3A%22CentOS%22%2C%22family%22%3A%22RedHat%22%2C%22release%22%3A%7B%22major%22%3A%226%22%2C%22minor%22%3A%225%22%2C%22full%22%3A%226.5%22%7D%7D%2C%22macaddress%22%3A%2200%3A50%3A56%3A8F%3AE0%3A6D%22%2C%22osfamily%22%3A%22RedHat%22%2C%22augeasversion%22%3A%221.3.0%22%2C%22uptime_seconds%22%3A33194%2C%22uptime%22%3A%229%3A13+hours%22%2C%22path%22%3A%22%2Fusr%2Flocal%2Fsbin%3A%2Fusr%2Flocal%2Fbin%3A%2Fsbin%3A%2Fbin%3A%2Fusr%2Fsbin%3A%2Fusr%2Fbin%3A%2Froot%2Fbin%3A%2Fopt%2Fpuppetlabs%2Fpuppet%2Fbin%2F%22%2C%22memorysize%22%3A%223.74+GB%22%2C%22memoryfree%22%3A%223.54+GB%22%2C%22swapsize%22%3A%223.94+GB%22%2C%22swapfree%22%3A%223.94+GB%22%2C%22swapsize_mb%22%3A%224031.99%22%2C%22swapfree_mb%22%3A%224031.99%22%2C%22memorysize_mb%22%3A%223832.70%22%2C%22memoryfree_mb%22%3A%223628.07%22%2C%22processors%22%3A%7B%22models%22%3A%5B%22Intel%28R%29+Xeon%28R%29+CPU+E5-2680+v2+%40+2.80GHz%22%2C%22Intel%28R%29+Xeon%28R%29+CPU+E5-2680+v2+%40+2.80GHz%22%5D%2C%22count%22%3A2%2C%22physicalcount%22%3A2%7D%2C%22kernelversion%22%3A%222.6.32%22%2C%22physicalprocessorcount%22%3A2%2C%22id%22%3A%22root%22%2C%22boardmanufacturer%22%3A%22Intel+Corporation%22%2C%22boardproductname%22%3A%22440BX+Desktop+Reference+Platform%22%2C%22boardserialnumber%22%3A%22None%22%2C%22bios_vendor%22%3A%22Phoenix+Technologies+LTD%22%2C%22bios_version%22%3A%226.00%22%2C%22bios_release_date%22%3A%2207%2F30%2F2013%22%2C%22manufacturer%22%3A%22VMware%2C+Inc.%22%2C%22productname%22%3A%22VMware+Virtual+Platform%22%2C%22serialnumber%22%3A%22VMware-42+0f+89+e2+f1+73+cb+71-6e+a6+79+26+d6+be+8e+0f%22%2C%22uuid%22%3A%22420F89E2-F173-CB71-6EA6-7926D6BE8E0F%22%2C%22type%22%3A%22Other%22%2C%22selinux%22%3Atrue%2C%22selinux_enforced%22%3Atrue%2C%22selinux_policyversion%22%3A%2224%22%2C%22selinux_current_mode%22%3A%22enforcing%22%2C%22selinux_config_mode%22%3A%22enforcing%22%2C%22selinux_config_policy%22%3A%22targeted%22%2C%22network_eth0%22%3A%2210.32.112.0%22%2C%22network_lo%22%3A%22127.0.0.0%22%2C%22hardwareisa%22%3A%22x86_64%22%2C%22hostname%22%3A%22stfui0skrwbvd7n%22%2C%22operatingsystemmajrelease%22%3A%226%22%2C%22interfaces%22%3A%22eth0%2Clo%22%2C%22ipaddress_eth0%22%3A%2210.32.114.124%22%2C%22macaddress_eth0%22%3A%2200%3A50%3A56%3A8F%3AE0%3A6D%22%2C%22netmask_eth0%22%3A%22255.255.240.0%22%2C%22mtu_eth0%22%3A1500%2C%22ipaddress_lo%22%3A%22127.0.0.1%22%2C%22netmask_lo%22%3A%22255.0.0.0%22%2C%22mtu_lo%22%3A16436%2C%22blockdevice_sr0_size%22%3A1073741312%2C%22blockdevice_sr0_vendor%22%3A%22NECVMWar%22%2C%22blockdevice_sr0_model%22%3A%22VMware+IDE+CDR10%22%2C%22blockdevice_sda_size%22%3A8589934592%2C%22blockdevice_sda_vendor%22%3A%22VMware%22%2C%22blockdevice_sda_model%22%3A%22Virtual+disk%22%2C%22blockdevice_sdb_size%22%3A8589934592%2C%22blockdevice_sdb_vendor%22%3A%22VMware%22%2C%22blockdevice_sdb_model%22%3A%22Virtual+disk%22%2C%22blockdevices%22%3A%22sda%2Csdb%2Csr0%22%2C%22ps%22%3A%22ps+-ef%22%2C%22partitions%22%3A%7B%22sda1%22%3A%7B%22uuid%22%3A%22c9b8c4a4-7c49-4cb0-b7ee-6dd795e27c87%22%2C%22size%22%3A%221024000%22%2C%22mount%22%3A%22%2Fboot%22%2C%22filesystem%22%3A%22ext4%22%7D%2C%22sda2%22%3A%7B%22size%22%3A%2215751168%22%2C%22filesystem%22%3A%22LVM2_member%22%7D%2C%22sdb1%22%3A%7B%22size%22%3A%2216771797%22%2C%22filesystem%22%3A%22LVM2_member%22%7D%7D%2C%22timezone%22%3A%22PDT%22%2C%22domain%22%3A%22delivery.puppetlabs.net%22%2C%22rubyplatform%22%3A%22x86_64-linux%22%2C%22kernelrelease%22%3A%222.6.32-431.11.2.el6.x86_64%22%2C%22system_uptime%22%3A%7B%22seconds%22%3A33194%2C%22hours%22%3A9%2C%22days%22%3A0%2C%22uptime%22%3A%229%3A13+hours%22%7D%2C%22fqdn%22%3A%22stfui0skrwbvd7n.delivery.puppetlabs.net%22%2C%22uptime_days%22%3A0%2C%22sshdsakey%22%3A%22AAAAB3NzaC1kc3MAAACBAJGJ%2BwHqAvYTv3VEzhPo3rwiaVxesMSstvufqZIYNLci54bEy7Dlq%2B%2BscLFU7EjqhlnGG0HWZ%2BaHQpDY8TvvsRIw8Q9nyxHAonk0EtHu4RCF6MH1lo0IeAh12A0vEpaVgpQjKisfWuH%2FIQEi1wCCaVL0lsLc5CLe1wE%2ByKqWuyVrAAAAFQD%2BF89mMng0ZXHd9NKbsZO5LQ5vcQAAAIAN6ysU1N1SASyGwtWuAnkRKxusYgCpQ0L7hx7shXHiQ69WoQxzgUUb5AdF%2B%2BkMQdplcqrD2MIf%2B6hk5o4kzkPTEJTpfl7l%2Fqp2L6znDR5yjz%2BG4b499eD3UGmlLIOgb1R7v%2FmS7Q3Y0XYsh1nBJyupOiTIMT1g6f7pQkA%2F9eimgwAAAIAiqkmEyA%2B8HRxg02zyPVG3z0RBFQnqnjLO8GaVFLq%2B3j5HTYgHuyktn2Js2Qke0j8bJ7gs%2F9Zaxq2dxC9BCZV29VAtmp7DO6lZgh3qwvA1uUKraO2J5zzWZHhJ2c9%2FapGtySBeOD1lOgGiXLkn5x4R09kLs56f5n%2Bax2kVa4qs3A%3D%3D%22%2C%22sshfp_dsa%22%3A%22SSHFP+2+1+8ebb6d9078da9da416723cac88c46bca6fe0ec54%5CnSSHFP+2+2+fd2bf6b3b04a115a7c8368a7f7e7738cf41d9e4c3eaf13033a38a53fe119ac69%22%2C%22sshrsakey%22%3A%22AAAAB3NzaC1yc2EAAAABIwAAAQEAr2ywcLVQDql7LcLz8DZvJLWuEdb86cwe%2Fq8TVqd7E1V0fKvXhZBXUN1aGeuvY%2BewfnlYh79ioDvslGCSh452caet3JljzhtU6mFtTpPm5FPofZ9a5SbR4oC5abFe8WH19KGI%2FHSsXEGqtNwNAcX6kfJSgcCRcPv%2BJg0rO4Goncv8hLEv%2Bek%2BizVpuAPPBvgHN1QLlfSlN0rlYvn62WDs0ecYTGpmy03JisfYubefJ25roOFxakx8NAdajb1Ce5IV7GxEn5BSe9mjGPI4UvDFYtDEMeKhDl8eKxICfcei8X6uUfunr1N4kIjn3Q78aloCFhzn37OSI71rjmYISOq3JQ%3D%3D%22%2C%22sshfp_rsa%22%3A%22SSHFP+1+1+c48ea7d5f6f38b3797e1e672f98ddf4d31796456%5CnSSHFP+1+2+b953c17a0af98e6fb1f3d06f2cc1e386a54e4868b2ea688ff950f4b8c5ed354a%22%2C%22gid%22%3A%22root%22%2C%22rubyversion%22%3A%222.1.6%22%2C%22filesystems%22%3A%22ext4%2Ciso9660%22%2C%22facterversion%22%3A%222.4.4%22%2C%22rubysitedir%22%3A%22%2Fopt%2Fpuppetlabs%2Fpuppet%2Flib%2Fruby%2Fsite_ruby%2F2.1.0%22%2C%22kernelmajversion%22%3A%222.6%22%2C%22uptime_hours%22%3A9%2C%22processor0%22%3A%22Intel%28R%29+Xeon%28R%29+CPU+E5-2680+v2+%40+2.80GHz%22%2C%22processor1%22%3A%22Intel%28R%29+Xeon%28R%29+CPU+E5-2680+v2+%40+2.80GHz%22%2C%22processorcount%22%3A2%2C%22netmask%22%3A%22255.255.240.0%22%2C%22ipaddress%22%3A%2210.32.114.124%22%2C%22operatingsystemrelease%22%3A%226.5%22%2C%22clientcert%22%3A%22stfui0skrwbvd7n.delivery.puppetlabs.net%22%2C%22clientversion%22%3A%224.1.0%22%2C%22clientnoop%22%3Afalse%7D%2C%22timestamp%22%3A%222015-05-22T10%3A14%3A29.340394764-07%3A00%22%2C%22expiration%22%3A%222025-05-22T10%3A44%3A29.340744715-07%3A00%22%7D")
			.formParam("transaction_uuid", "e1c0a4a6-b57f-4dd9-b3bc-5d127fc134b3")
			.formParam("fail_on_404", "true"))
		.pause(2)
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero1/catalog_zero1_impl24.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero1/catalog_zero1_impl71.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero1/catalog_zero1_impl83.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero2/catalog_zero2_impl51.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero3/catalog_zero3_impl23.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero3/catalog_zero3_impl32.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero3/catalog_zero3_impl74.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero4/catalog_zero4_impl13.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero5/catalog_zero5_impl22.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero5/catalog_zero5_impl42.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero5/catalog_zero5_impl43.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero5/catalog_zero5_impl52.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero6/catalog_zero6_impl32.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero6/catalog_zero6_impl54.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero7/catalog_zero7_impl32.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero7/catalog_zero7_impl34.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero7/catalog_zero7_impl82.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero7/catalog_zero7_impl85.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero7/catalog_zero7_impl87.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero8/catalog_zero8_impl11.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero8/catalog_zero8_impl13.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero8/catalog_zero8_impl33.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero8/catalog_zero8_impl81.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero9/catalog_zero9_impl63.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero9/catalog_zero9_impl72.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero9/catalog_zero9_impl84.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero10/catalog_zero10_impl13.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero10/catalog_zero10_impl22.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero10/catalog_zero10_impl41.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero10/catalog_zero10_impl71.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero10/catalog_zero10_impl83.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero10/catalog_zero10_impl85.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero11/catalog_zero11_impl11.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero11/catalog_zero11_impl21.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero11/catalog_zero11_impl24.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero11/catalog_zero11_impl62.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero11/catalog_zero11_impl84.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero12/catalog_zero12_impl33.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero12/catalog_zero12_impl82.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero12/catalog_zero12_impl86.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero12/catalog_zero12_impl87.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero13/catalog_zero13_impl51.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero13/catalog_zero13_impl54.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero13/catalog_zero13_impl74.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero13/catalog_zero13_impl83.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero13/catalog_zero13_impl84.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero13/catalog_zero13_impl86.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero14/catalog_zero14_impl72.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero15/catalog_zero15_impl62.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero15/catalog_zero15_impl72.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero15/catalog_zero15_impl73.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero16/catalog_zero16_impl33.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero16/catalog_zero16_impl83.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero16/catalog_zero16_impl85.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero17/catalog_zero17_impl13.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero17/catalog_zero17_impl87.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero18/catalog_zero18_impl14.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero18/catalog_zero18_impl23.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero18/catalog_zero18_impl24.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero18/catalog_zero18_impl32.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero18/catalog_zero18_impl84.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero19/catalog_zero19_impl12.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero19/catalog_zero19_impl31.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero19/catalog_zero19_impl53.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero19/catalog_zero19_impl54.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero19/catalog_zero19_impl83.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero19/catalog_zero19_impl86.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero20/catalog_zero20_impl24.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero20/catalog_zero20_impl42.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero20/catalog_zero20_impl71.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero20/catalog_zero20_impl73.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero21/catalog_zero21_impl32.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero21/catalog_zero21_impl41.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero21/catalog_zero21_impl82.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero21/catalog_zero21_impl86.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero21/catalog_zero21_impl87.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero22/catalog_zero22_impl34.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero22/catalog_zero22_impl52.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero23/catalog_zero23_impl21.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero23/catalog_zero23_impl62.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero24/catalog_zero24_impl52.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero24/catalog_zero24_impl83.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero25/catalog_zero25_impl13.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero25/catalog_zero25_impl22.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero25/catalog_zero25_impl24.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero25/catalog_zero25_impl51.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero26/catalog_zero26_impl54.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero26/catalog_zero26_impl64.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero26/catalog_zero26_impl86.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero27/catalog_zero27_impl33.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero27/catalog_zero27_impl41.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero27/catalog_zero27_impl63.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero28/catalog_zero28_impl13.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero28/catalog_zero28_impl33.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))

val chain_1 = exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero28/catalog_zero28_impl51.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero28/catalog_zero28_impl72.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero28/catalog_zero28_impl84.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero29/catalog_zero29_impl71.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero29/catalog_zero29_impl86.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero30/catalog_zero30_impl34.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.exec(http("filemeta")
			.get("/puppet/v3/file_metadata/modules/catalog_zero30/catalog_zero30_impl85.txt?environment=production&links=manage&checksum_type=md5&source_permissions=ignore")
			.headers(headers_0))
		.pause(1)
		.exec((session:Session) => {
			session.set("reportTimestamp",
				LocalDateTime.now.toString(ISODateTimeFormat.dateTime()))
		})
		.exec((session:Session) => {
			session.set("transactionUuid",
				UUID.randomUUID().toString())
		})
		.exec(http("report")
			.put("/puppet/v3/report/stfui0skrwbvd7n.delivery.puppetlabs.net?environment=production&")
			.headers(headers_105)
			.body(reportBody))
					
	val scn = scenario("FOSSPuppetserver210CatalogZero").exec(
		chain_0, chain_1)

	// setUp(scn.inject(atOnceUsers(1))).protocols(httpProtocol)
}
