package com.puppetlabs.gatling.node_simulations

import java.util.UUID

import com.puppetlabs.gatling.runner.SimulationWithScenario
import org.joda.time.LocalDateTime
import org.joda.time.format.ISODateTimeFormat

import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._

class PE33PerfMedium extends SimulationWithScenario {

//	val httpProtocol = http
//		.baseURL("https://puppetserver-perf-sut54.delivery.puppetlabs.net:8140")
//		.connection("close")

	val headers_all = Map("Connection" -> "close")

	val headers_2 = Map(
		"Accept" -> "pson, b64_zlib_yaml, yaml, dot, raw",
		"Connection" -> "close"
	)

	val headers_127 = Map(
		"Accept" -> "pson, yaml",
		"Content-Type" -> "text/pson",
		"Connection" -> "close"
	)

//    val uri1 = "https://puppetserver-perf-sut54.delivery.puppetlabs.net:8140/production"

	val reportBody = ELFileBody("PE33PerfMedium_0127_request.txt")

	val chain_0 = exec(http("node")
			.get("/production/node/${node}?transaction_uuid=080a6528-a4ee-43aa-91e0-3897492b971a&fail_on_404=true"))
		.pause(2)
		.exec(http("filemeta plugins")
			.get("/production/file_metadatas/plugins?links=manage&recurse=true&ignore=.svn&ignore=CVS&ignore=.git&checksum_type=md5")
			.headers(headers_all))
		.pause(3)
		.exec(http("catalog")
			.post("/production/catalog/${node}")
			.headers(headers_2)
			.formParam("facts_format", "pson")
			.formParam("facts", "%7B%22name%22%3A%22${node}%22%2C%22values%22%3A%7B%22architecture%22%3A%22x86_64%22%2C%22augeasversion%22%3A%221.1.0%22%2C%22kernel%22%3A%22Linux%22%2C%22blockdevice_fd0_size%22%3A%224096%22%2C%22blockdevice_sda_size%22%3A%2217179869184%22%2C%22blockdevice_sda_vendor%22%3A%22VMware%22%2C%22blockdevice_sda_model%22%3A%22Virtual+disk%22%2C%22blockdevice_sr0_size%22%3A%221073741312%22%2C%22blockdevice_sr0_vendor%22%3A%22NECVMWar%22%2C%22blockdevice_sr0_model%22%3A%22VMware+IDE+CDR10%22%2C%22blockdevices%22%3A%22fd0%2Csda%2Csr0%22%2C%22domain%22%3A%22delivery.puppetlabs.net%22%2C%22osfamily%22%3A%22RedHat%22%2C%22operatingsystem%22%3A%22CentOS%22%2C%22lsbdistid%22%3A%22CentOS%22%2C%22facterversion%22%3A%221.7.5%22%2C%22filesystems%22%3A%22xfs%22%2C%22fqdn%22%3A%22duz279yeswbfsyw.delivery.puppetlabs.net%22%2C%22hardwareisa%22%3A%22x86_64%22%2C%22hardwaremodel%22%3A%22x86_64%22%2C%22hostname%22%3A%22duz279yeswbfsyw%22%2C%22id%22%3A%22root%22%2C%22ipaddress%22%3A%2210.32.117.199%22%2C%22kernelmajversion%22%3A%223.10%22%2C%22kernelrelease%22%3A%223.10.0-123.4.2.el7.x86_64%22%2C%22kernelversion%22%3A%223.10.0%22%2C%22lsbdistcodename%22%3A%22Core%22%2C%22lsbdistdescription%22%3A%22CentOS+Linux+release+7.0.1406+%28Core%29+%22%2C%22lsbdistrelease%22%3A%227.0.1406%22%2C%22lsbmajdistrelease%22%3A%227%22%2C%22lsbrelease%22%3A%22%3Acore-4.1-amd64%3Acore-4.1-noarch%3Acxx-4.1-amd64%3Acxx-4.1-noarch%3Adesktop-4.1-amd64%3Adesktop-4.1-noarch%3Alanguages-4.1-amd64%3Alanguages-4.1-noarch%3Aprinting-4.1-amd64%3Aprinting-4.1-noarch%22%2C%22boardmanufacturer%22%3A%22Intel+Corporation%22%2C%22boardproductname%22%3A%22440BX+Desktop+Reference+Platform%22%2C%22boardserialnumber%22%3A%22None%22%2C%22bios_vendor%22%3A%22Phoenix+Technologies+LTD%22%2C%22bios_version%22%3A%226.00%22%2C%22bios_release_date%22%3A%2207%2F30%2F2013%22%2C%22manufacturer%22%3A%22VMware%2C+Inc.%22%2C%22productname%22%3A%22VMware+Virtual+Platform%22%2C%22serialnumber%22%3A%22VMware-42+0f+d8+80+9e+a7+5f+e7-78+11+17+96+12+58+2a+d4%22%2C%22uuid%22%3A%22420FD880-9EA7-5FE7-7811-179612582AD4%22%2C%22type%22%3A%22Other%22%2C%22memorysize%22%3A%223.70+GB%22%2C%22memoryfree%22%3A%223.17+GB%22%2C%22swapsize%22%3A%221.60+GB%22%2C%22swapfree%22%3A%221.60+GB%22%2C%22swapsize_mb%22%3A%221640.00%22%2C%22swapfree_mb%22%3A%221640.00%22%2C%22memorysize_mb%22%3A%223792.76%22%2C%22memoryfree_mb%22%3A%223243.31%22%2C%22memorytotal%22%3A%223.70+GB%22%2C%22operatingsystemmajrelease%22%3A%227%22%2C%22operatingsystemrelease%22%3A%227.0.1406%22%2C%22path%22%3A%22%2Fusr%2Flib64%2Fqt-3.3%2Fbin%3A%2Fusr%2Flocal%2Fsbin%3A%2Fusr%2Flocal%2Fbin%3A%2Fusr%2Fsbin%3A%2Fusr%2Fbin%3A%2Froot%2Fbin%3A%2Fsbin%22%2C%22physicalprocessorcount%22%3A%222%22%2C%22processor0%22%3A%22Intel%28R%29+Xeon%28R%29+CPU+E5-2680+v2+%40+2.80GHz%22%2C%22processor1%22%3A%22Intel%28R%29+Xeon%28R%29+CPU+E5-2680+v2+%40+2.80GHz%22%2C%22processorcount%22%3A%222%22%2C%22ps%22%3A%22ps+-ef%22%2C%22puppetversion%22%3A%223.6.2+%28Puppet+Enterprise+3.3.2%29%22%2C%22rubysitedir%22%3A%22%2Fopt%2Fpuppet%2Flib%2Fruby%2Fsite_ruby%2F1.9.1%22%2C%22rubyversion%22%3A%221.9.3%22%2C%22selinux%22%3A%22true%22%2C%22selinux_enforced%22%3A%22true%22%2C%22selinux_policyversion%22%3A%2228%22%2C%22selinux_current_mode%22%3A%22enforcing%22%2C%22selinux_config_mode%22%3A%22enforcing%22%2C%22selinux_config_policy%22%3A%22unknown%22%2C%22selinux_mode%22%3A%22unknown%22%2C%22sshrsakey%22%3A%22AAAAB3NzaC1yc2EAAAADAQABAAABAQDBKcjgii7T6UEVEUZGYsI52NZmzbJABGJHqnR%2BxeAlCz0H939xVgQHK7%2FnCq3joxmVLwTKd7DTCqMn9x1Q7MJ9ERJWIUCgwPNdS4YDfq52nddk%2BFNtAfhiWsnAjS1MNGUDUcAxakOjvcWp%2FpPG6cGIq8gnnMdY3Nemlq3i3b5zruvv1z77Mq2rPthfibEP5kI3Hwt%2FrrcyIuUWiE5oGh0CBw4hLdB3BZMu0OzPcbKW%2Fn8rM0krYB6t1aC5AJy%2FdIJrFVyjbvI6XFBfYm2eqMM0eZGaerpAt%2Bd%2B%2FcmiFJF2PLAb5HxkeTpbm%2BgaiqfkI8UDsjc77wGvnvC3M3nz%2F6uL%22%2C%22sshfp_rsa%22%3A%22SSHFP+1+1+e0f23ba5ff40fa9bc18c4fbb820c4f6afdef335d%5CnSSHFP+1+2+9333a82d26cfb2e1e89368e8061eef1c48a87da677395cf02f0ff1b72d862008%22%2C%22sshecdsakey%22%3A%22AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLqjIT44wYmXSU%2Bvc5zsUUxf00XTllP22tjIwChv3sW7uNhtqLXc1bagOqpRLctiBi64bo%2F%2BCPvBJxUT3%2B5RWOc%3D%22%2C%22sshfp_ecdsa%22%3A%22SSHFP+3+1+d39b22b2e94886804feff4df669da23cdb358b58%5CnSSHFP+3+2+94a8328bce249921a53ffd36cb1d4b7b5a723949abebd554d7d0507e8c83e04c%22%2C%22timezone%22%3A%22PDT%22%2C%22uniqueid%22%3A%22200ac775%22%2C%22uptime%22%3A%2214%3A31+hours%22%2C%22uptime_days%22%3A%220%22%2C%22uptime_hours%22%3A%2214%22%2C%22uptime_seconds%22%3A%2252304%22%2C%22virtual%22%3A%22vmware%22%2C%22is_virtual%22%3A%22true%22%2C%22choco_install_path%22%3A%22C%3A%5C%5CProgramData%5C%5Cchocolatey%22%2C%22chocolateyversion%22%3A%220%22%2C%22custom_auth_conf%22%3A%22false%22%2C%22fake_domain%22%3A%22pgtomcat.mycompany.org%22%2C%22function%22%3A%22app%22%2C%22group%22%3A%22pgtomcat%22%2C%22ip6tables_version%22%3A%221.4.21%22%2C%22iptables_version%22%3A%221.4.21%22%2C%22java_default_home%22%3A%22%2Fusr%2Flib%2Fjvm%2Fjava-1.7.0-openjdk-1.7.0.111-2.6.7.2.el7_2.x86_64%22%2C%22java_libjvm_path%22%3A%22%2Fusr%2Flib%2Fjvm%2Fjava-1.7.0-openjdk-1.7.0.111-2.6.7.2.el7_2.x86_64%2Fjre%2Flib%2Famd64%2Fserver%22%2C%22java_major_version%22%3A%227%22%2C%22java_patch_level%22%3A%22111%22%2C%22java_version%22%3A%221.7.0_111%22%2C%22package_provider%22%3A%22yum%22%2C%22pe_build%22%3A%223.3.2%22%2C%22pe_postgres_default_version%22%3A%22unknown%22%2C%22pe_version%22%3A%223.3.2%22%2C%22is_pe%22%3A%22true%22%2C%22pe_major_version%22%3A%223%22%2C%22pe_minor_version%22%3A%223%22%2C%22pe_patch_version%22%3A%222%22%2C%22platform_tag%22%3A%22el-7-x86_64%22%2C%22puppet_vardir%22%3A%22%2Fvar%2Fopt%2Flib%2Fpe-puppet%22%2C%22root_home%22%3A%22%2Froot%22%2C%22rsyslog_version%22%3A%227.4.7%22%2C%22service_provider%22%3A%22systemd%22%2C%22stage%22%3A%22prod%22%2C%22staging_http_get%22%3A%22curl%22%2C%22whereami%22%3A%22portland%22%2C%22clientcert%22%3A%22${node}%22%2C%22clientversion%22%3A%223.6.2+%28Puppet+Enterprise+3.3.2%29%22%2C%22clientnoop%22%3A%22false%22%7D%2C%22timestamp%22%3A%222016-08-06+20%3A12%3A45+-0700%22%2C%22expiration%22%3A%222116-08-06T20%3A42%3A45.308154666-07%3A00%22%7D")
			.formParam("transaction_uuid", "080a6528-a4ee-43aa-91e0-3897492b971a")
			.formParam("fail_on_404", "true"))
		.pause(3)
		.exec(http("filemeta")
			.get("/production/file_metadata/modules/epel/RPM-GPG-KEY-EPEL-7?links=manage&source_permissions=use")
			.headers(headers_all))
		.pause(1)
		.exec(http("filemeta")
			.get("/production/file_metadata/modules/motd/banner.txt?links=manage&source_permissions=use")
			.headers(headers_all))
		.pause(394 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadata/modules/postgresql/validate_postgresql_connection.sh?links=manage&source_permissions=use")
			.headers(headers_all))
		.pause(476 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen0?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(475 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(438 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen1?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(415 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(416 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen2?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(464 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(452 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen3?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(371 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(441 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen4?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(328 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(417 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen5?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(420 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(457 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen6?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(456 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(480 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen7?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(427 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(420 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen8?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(521 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(420 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen9?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(419 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(426 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen10?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(456 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(427 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen11?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(427 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(441 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen12?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(342 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(401 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen13?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(414 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(419 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen14?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(400 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(424 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen15?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(421 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(444 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen16?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(415 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(420 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen17?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(426 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(415 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen18?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(484 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(410 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen19?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(391 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(433 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen20?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(455 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(450 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen21?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(392 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(446 milliseconds)

val chain_1 = exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen22?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(393 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(421 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen23?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(398 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(372 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen24?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(409 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(374 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen25?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(398 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(440 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen26?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(408 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(419 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen27?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(399 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(355 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen28?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(404 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(1)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen29?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(447 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(455 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen30?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(418 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(427 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen31?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(407 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(406 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen32?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(437 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(405 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen33?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(412 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(455 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen34?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(375 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(341 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen35?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(372 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(413 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen36?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(419 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(418 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen37?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(412 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(470 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen38?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(406 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(428 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen39?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(385 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(452 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen40?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(420 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(431 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen41?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(416 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(471 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen42?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(370 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(403 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen43?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(376 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(355 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen44?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(367 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(340 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen45?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(403 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(467 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen46?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(397 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(433 milliseconds)

val chain_2 = exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen47?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(411 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(428 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen48?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(415 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(414 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen49?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(421 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(475 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen50?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(408 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(449 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen51?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(419 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(422 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen52?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(592 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(505 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen53?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(424 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(455 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen54?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(410 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(423 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen55?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(415 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(424 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen56?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(400 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(422 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen57?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(462 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(407 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen58?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(404 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(412 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdirs/citizen59?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all)
			.check(status.is(404)))
		.pause(402 milliseconds)
		.exec(http("filemeta")
			.get("/production/file_metadatas/modules/userwrapper/userdir_default?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(587 milliseconds)
		.exec(http("filemeta mco plugins")
			.get("/production/file_metadatas/modules/pe_mcollective/plugins?links=manage&recurse=true&checksum_type=md5")
			.headers(headers_all))
		.pause(4)
		.exec((session:Session) => {
			session.set("reportTimestamp",
				LocalDateTime.now.toString(ISODateTimeFormat.dateTime()))
		})
		.exec((session:Session) => {
			session.set("transactionUuid",
				UUID.randomUUID().toString())
		})
		.exec(http("report")
			.put("/production/report/${node}")
			.headers(headers_127)
			.body(reportBody))
					
	val scn = scenario("PE33PerfMedium").exec(
		chain_0, chain_1, chain_2)

//	setUp(scn.inject(atOnceUsers(1))).protocols(httpProtocol)
}
