#!/usr/bin/env bash

set -e

echo "
This bash file will generate a csv file with node names for your gatling feeder simulation. You will give it a number, and it will generate a hostname of node0,node1,....,nodeX. Then change the file in your gatling scenario to use the new csv file.
PRESS ENTER
"
read

echo -n "How many node hostnames would you like to generate=? "
read TOTALNODES
echo "Generating $TOTALNODES node hostnames and placing file into user-files/data/nodes.$TOTALNODES.csv"

TOTAL=`expr $TOTALNODES - 1`

touch nodes.$TOTALNODES.csv
echo "node" >> nodes.$TOTALNODES.csv

for i in `seq 0 $TOTAL`;
do
  echo "node$i" >> nodes.$TOTALNODES.csv
done

echo "
File generation complete! Please move the new file to user-files/data, and replace the file name in your gatling scenario scala file to match the file generated by this script."
