node {
    checkout scm
    pipeline = load 'jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy'
}

pipeline.multipass_pipeline([
//        [job_name: 'pe-couch-medium-no-static-catalogs',
//         gatling_simulation_config: '../simulation-runner/config/scenarios/pe-couch-medium-no-static-catalogs-1000-2-hours.json',
//         server_version: [
//                 type: "pe",
//                 pe_version: "2016.2.0"
//         ],
//         code_deploy: [
//                 type: "r10k",
//                 control_repo: "git@github.com:puppetlabs/puppetlabs-puppetserver_perf_control.git",
//                 basedir: "/etc/puppetlabs/code-staging/environments",
//                 environments: ["production"],
//                 hiera_config_source_file: "/etc/puppetlabs/code-staging/environments/production/root_files/hiera.yaml"
//         ],
//         server_java_args: "-Xms12g -Xmx12g",
//         puppet_settings: [
//                 master: [
//                    "static_catalogs": "false"
//                 ]
//         ],
//         background_scripts: [
//                 "./jenkins-jobs/common/scripts/background/curl-server-metrics-loop.sh"
//         ],
//         archive_sut_files: [
//                 "/var/log/puppetlabs/puppetserver/metrics.json"
//         ]
//        ],
        [job_name: 'pe-couch-static-catalogs',
         gatling_simulation_config: '../simulation-runner/config/scenarios/pe-couch-medium-1500-1-hour.json',
         server_version: [
                 type: "pe",
                 pe_version: "2016.2.0"
         ],
         code_deploy: [
                 type: "r10k",
                 control_repo: "git@github.com:puppetlabs/puppetlabs-puppetserver_perf_control.git",
                 basedir: "/etc/puppetlabs/code-staging/environments",
                 environments: ["production"],
                 hiera_config_source_file: "/etc/puppetlabs/code-staging/environments/production/root_files/hiera.yaml"
         ],
         server_java_args: "-Xms12g -Xmx12g",
         background_scripts: [
                 "./jenkins-jobs/common/scripts/background/curl-server-metrics-loop.sh"
         ],
         archive_sut_files: [
                 "/var/log/puppetlabs/puppetserver/metrics.json"
         ]
        ]
])
