node {
    checkout scm
    pipeline = load 'jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy'
}

def no_static_catalogs_base_config() {
    [server_version: [
             type: "pe",
             pe_version: "2016.2.1"
     ],
     code_deploy: [
             type: "r10k",
             control_repo: "git@github.com:puppetlabs/puppetlabs-puppetserver_perf_control.git",
             basedir: "/etc/puppetlabs/code-staging/environments",
             environments: ["production"],
             hiera_config_source_file: "/etc/puppetlabs/code-staging/environments/production/root_files/hiera.yaml"
     ],
     server_heap_settings: "-Xms12g -Xmx12g",
     puppet_settings: [
             master: [
                     "static_catalogs": "false"
             ]
     ],
     background_scripts: [
             "./jenkins-jobs/common/scripts/background/curl-server-metrics-loop.sh"
     ],
     archive_sut_files: [
             "/var/log/puppetlabs/puppetserver/metrics.json"
     ]
    ]
}

def static_catalogs_base_config() {
    [server_version: [
             type: "pe",
             pe_version: "2016.2.1"
     ],
     code_deploy: [
             type: "r10k",
             control_repo: "git@github.com:puppetlabs/puppetlabs-puppetserver_perf_control.git",
             basedir: "/etc/puppetlabs/code-staging/environments",
             environments: ["production"],
             hiera_config_source_file: "/etc/puppetlabs/code-staging/environments/production/root_files/hiera.yaml"
     ],
     server_heap_settings: "-Xms12g -Xmx12g",
     background_scripts: [
             "./jenkins-jobs/common/scripts/background/curl-server-metrics-loop.sh"
     ],
     archive_sut_files: [
             "/var/log/puppetlabs/puppetserver/metrics.json"
     ]
    ]
}

no_static_catalogs_250 = no_static_catalogs_base_config()
no_static_catalogs_250.put('job_name', 'pe-couch-no-static-250')
no_static_catalogs_250.put('gatling_simulation_config', '../simulation-runner/config/scenarios/pe-couch-medium-no-static-catalogs-250-2-hours.json')

static_catalogs_500 = static_catalogs_base_config()
static_catalogs_500.put('job_name', 'pe-couch-static-500')
static_catalogs_500.put('gatling_simulation_config', '../simulation-runner/config/scenarios/pe-couch-medium-500-2-hours.json')

no_static_catalogs_500 = no_static_catalogs_base_config()
no_static_catalogs_500.put('job_name', 'pe-couch-no-static-500')
no_static_catalogs_500.put('gatling_simulation_config', '../simulation-runner/config/scenarios/pe-couch-medium-no-static-catalogs-500-2-hours.json')

static_catalogs_1000 = static_catalogs_base_config()
static_catalogs_1000.put('job_name', 'pe-couch-static-1000')
static_catalogs_1000.put('gatling_simulation_config', '../simulation-runner/config/scenarios/pe-couch-medium-1000-2-hours.json')

no_static_catalogs_1000 = no_static_catalogs_base_config()
no_static_catalogs_1000.put('job_name', 'pe-couch-no-static-1000')
no_static_catalogs_1000.put('gatling_simulation_config', '../simulation-runner/config/scenarios/pe-couch-medium-no-static-catalogs-1000-2-hours.json')

static_catalogs_1250 = static_catalogs_base_config()
static_catalogs_1250.put('job_name', 'pe-couch-static-1250')
static_catalogs_1250.put('gatling_simulation_config', '../simulation-runner/config/scenarios/pe-couch-medium-1250-2-hours.json')

pipeline.multipass_pipeline([
    no_static_catalogs_250,
    static_catalogs_500,
    no_static_catalogs_500,
    static_catalogs_1000,
    no_static_catalogs_1000,
    static_catalogs_1250
])
