node {
    checkout scm

    stage '001-create-files'
    sh "echo 'hello!' > hello.txt"
    sh "echo 'hello again!' > hello_again.txt"
    sh "mkdir greetings; echo 'hi' > greetings/hi.txt"
    sh "mkdir -p greetings/foo/bar; echo 'foo' > greetings/foo/bar/foo.txt"

    stage '002-upload-to-s3'
    step([
        $class: 'S3BucketPublisher',
        entries: [
            [
                bucket: 'puppetserver-perf-data',
                selectedRegion: 'us-west-1',
                sourceFile: 'hello.txt, hello_again.txt, greetings/**',
                storageClass: 'STANDARD',
            ]
        ],
        profileName: 'Jenkins_coordinator_machine_account'
    ])
}
