node {
    checkout scm
    pipeline = load 'jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy'
}

//pipeline.single_pipeline(
//        [job_name: 'pe33-medium',
//         gatling_simulation_config: '../simulation-runner/config/scenarios/pe33-medium-10.json',
//         server_version: [
//                 type: "pe",
//                 pe_version: "3.3.2"
//         ],
//         code_deploy: [
//                 type: "r10k",
//                 control_repo: "git@github.com:puppetlabs/puppetlabs-puppetserver_perf_control.git",
//                 basedir: "/etc/puppetlabs/puppet/environments",
//                 environments: ["production"],
//                 hiera_config_source_file: "/etc/puppetlabs/puppet/environments/production/root_files/hiera.yaml",
//                 hiera_config_datadir: "/etc/puppetlabs/puppet/environments/%{environment}/hieradata"
//         ]
//        ])

pipeline.multipass_pipeline([
        [job_name: 'pe33-medium',
         gatling_simulation_config: '../simulation-runner/config/scenarios/pe33-medium-10.json',
         server_version: [
                 type: "pe",
                 pe_version: "3.3.2"
         ],
         code_deploy: [
                 type: "r10k",
                 control_repo: "git@github.com:puppetlabs/puppetlabs-puppetserver_perf_control.git",
                 basedir: "/etc/puppetlabs/puppet/environments",
                 environments: ["production"],
                 hiera_config_source_file: "/etc/puppetlabs/puppet/environments/production/root_files/hiera.yaml",
                 hiera_config_datadir: "/etc/puppetlabs/puppet/environments/%{environment}/hieradata"
         ]],
        [job_name: 'pe-couch-medium',
         gatling_simulation_config: '../simulation-runner/config/scenarios/pe-couch-medium-10.json',
         server_version: [
                 type: "pe",
                 pe_version: "2016.2.0"
         ],
         code_deploy: [
                 type: "r10k",
                 control_repo: "git@github.com:puppetlabs/puppetlabs-puppetserver_perf_control.git",
                 basedir: "/etc/puppetlabs/code-staging/environments",
                 environments: ["production"],
                 hiera_config_source_file: "/etc/puppetlabs/code-staging/environments/production/root_files/hiera.yaml"
         ]]
])
