node {
    checkout scm
    pipeline = load 'jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy'
}

pipeline.single_pipeline([
        job_name: 'oss-latest',
        gatling_simulation_config: '../simulation-runner/config/scenarios/pe-couch-medium-10.json',
        server_version: [
                type: "oss",
                version: "latest"
        ],
        code_deploy: [
                type: "r10k",
                control_repo: "git@github.com:puppetlabs/puppetlabs-puppetserver_perf_control.git",
                basedir: "/etc/puppetlabs/code/environments",
                environments: ["production"],
                hiera_config_source_file: "/etc/puppetlabs/code/environments/production/root_files/hiera.yaml"
        ]
])
