node {
    checkout scm
    pipeline = load 'jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy'
}

pipeline.single_pipeline([
        job_name: 'oss-stable',
        gatling_simulation_config: '../simulation-runner/config/scenarios/foss25x-medium-1250-2-hours.json',
        server_version: [
                type: "oss",
                version: "stable"
        ],
        agent_version: [
                version: "latest-release"
        ],
        code_deploy: [
                type: "r10k",
                control_repo: "git@github.com:puppetlabs/puppetlabs-puppetserver_perf_control.git",
                basedir: "/etc/puppetlabs/code/environments",
                environments: ["production"],
                hiera_config_source_file: "/etc/puppetlabs/code/environments/production/root_files/hiera.yaml"
        ],
        background_scripts: [
                "./jenkins-jobs/common/scripts/background/curl-server-metrics-loop.sh"
        ],
        archive_sut_files: [
                "/var/log/puppetlabs/puppetserver/metrics.json"
        ]
])
