#! /bin/sh

id=slv
type=scale
tag=${id}-"$@"

source=${PWD}/gatling-puppet-load-test/results/${type}
results=${source}/"$@"

ruby /home/centos/puppet-metrics-viewer/json2graphite.rb --pattern ${results}/puppet-metrics-collector/**/*.json --convert-to influxdb --netcat localhost --influx-db puppet_metrics --server-tag ${tag}

