#! /bin/sh

######################################################################################
# call this script with the name of the result directory you want to copy (i.e. `./res PERF_1555458238`)
######################################################################################

# set this to 'perf', 'scale', 'soak', etc...
type=perf

# set this with a name that corresponds to this instance (i.e. 'slv-321a')
id=slv

# this section uses the parameters specified above and should not require updates per instance
date=$(date +"%Y-%m-%d")
source=${PWD}/gatling-puppet-load-test/results/${type}
results=${source}/"$@"
dest=/usr/share/nginx/html/gplt/${type}/${id}/${BEAKER_PE_VER}/${ABS_AWS_MOM_SIZE}

sudo mkdir -p ${dest}
sudo cp -r -L ${results} ${dest}

cd ${source} && tar czf "$@".tar.gz "$@"
sudo cp ${results}.tar.gz ${dest}
