#! /bin/sh

# remove the gatling-puppet-load-test directory in the current directory
# then clone the gatling-puppet-load-test repo into the current directory

timestamp=$(date +"%Y-%m-%d_%H-%M-%S")

echo "removing gatling-puppet-load-test"
rm -rf ./gatling-puppet-load-test

echo "cloning gatling-puppet-load-test"
git clone https://github.com/puppetlabs/gatling-puppet-load-test.git

echo "refresh complete; adding timestamp to gatling-puppet-load-test"
touch ./gatling-puppet-load-test/${timestamp}.txt
