node {
    checkout scm
    pipeline = load 'jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy'
}

pipeline.spin_up_puppetserver([
        job_name: 'spin-up-puppetserver',
        server_version: [
                type: "oss",
                version: "latest"
        ],
        agent_version: [
                version: "latest"
        ],
        code_deploy: [
                type: "r10k",
                control_repo: "git@github.com:puppetlabs/puppetlabs-puppetserver_perf_control.git",
                basedir: "/etc/puppetlabs/code/environments",
                // Environments is overridden for the empty catalog, as it needs a special environment with no modules in the Puppetfile
                environments: ["production"],
                hiera_config_source_file: "/etc/puppetlabs/code/environments/production/root_files/hiera.yaml"
        ],
        background_scripts: [
                "./jenkins-jobs/common/scripts/background/curl-server-metrics-loop.sh"
        ],
        jruby_jar: "/opt/puppetlabs/server/apps/puppetserver/jruby-9k.jar",
        hocon_settings: [
                  [
                    file: "/etc/puppetlabs/puppetserver/conf.d/puppetserver.conf",
                    path: "jruby-puppet.compile-mode",
                    value: "jit"
                  ]
        ],
        server_heap_settings: "-Xms2g -Xmx2g",
])
