source ENV['GEM_SOURCE'] || 'https://rubygems.org'

gem 'beaker', '~>3.2.0'
gem 'beaker-hostgenerator', '0.8.0'
gem 'beaker-pe', '~>1.4'

gem 'scooter', '~> 3.2.0'

if File.exists? "#{__FILE__}.local"
  eval(File.read("#{__FILE__}.local"), binding)
end
